
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Feb 25 14:10:20 EST 2015
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class A3Symbol {
  /* terminals */
  public static final int RBRACK = 17;
  public static final int SEMICOLON = 15;
  public static final int ELSE = 6;
  public static final int INT = 12;
  public static final int ISE = 21;
  public static final int READING = 4;
  public static final int LBRACK = 18;
  public static final int END = 9;
  public static final int RETURN = 7;
  public static final int IF = 5;
  public static final int QUOTEDSTRING = 2;
  public static final int ID = 22;
  public static final int WRITE = 3;
  public static final int BEGIN = 8;
  public static final int EQUALS = 19;
  public static final int STRING = 11;
  public static final int COMMA = 14;
  public static final int NUMBER = 23;
  public static final int EOF = 0;
  public static final int MULT = 16;
  public static final int MAIN = 10;
  public static final int error = 1;
  public static final int REAL = 13;
  public static final int NEQUALS = 20;
}

