
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Mar 21 15:12:27 EDT 2015
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class A4Symbol {
  /* terminals */
  public static final int RBRACK = 16;
  public static final int SEMICOLON = 13;
  public static final int ELSE = 5;
  public static final int SOP = 14;
  public static final int INT = 10;
  public static final int ISE = 20;
  public static final int READING = 3;
  public static final int LBRACK = 17;
  public static final int END = 8;
  public static final int RETURN = 6;
  public static final int QUOTEDSTRING = 24;
  public static final int IF = 4;
  public static final int ID = 21;
  public static final int WRITE = 2;
  public static final int BEGIN = 7;
  public static final int STRING = 23;
  public static final int EQUALS = 18;
  public static final int COMMA = 12;
  public static final int NUMBER = 22;
  public static final int EOF = 0;
  public static final int MAIN = 9;
  public static final int error = 1;
  public static final int MOP = 15;
  public static final int REAL = 11;
  public static final int NEQUALS = 19;
}

